<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPXqh3hM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPXqh3hM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPXqh3hM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPXqh3hM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPXqh3hM\App_KernelDevDebugContainer([
    'container.build_hash' => 'PXqh3hM',
    'container.build_id' => '53630bf2',
    'container.build_time' => 1581424554,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPXqh3hM');
